/** Generated by YAKINDU Statechart Tools code generator. */
package hu.bme.mit.yakindu.analysis.example;

import hu.bme.mit.yakindu.analysis.IStatemachine;
import hu.bme.mit.yakindu.analysis.ITimerCallback;

public interface IExampleStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseSt();
		
		public void raiseWh();
		
		public void raiseBl();
		
		public long getWhTime();
		
		public void setWhTime(long value);
		
		public long getBlTime();
		
		public void setBlTime(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
